# Change these first
owner: uptimey # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: JustPerfectHome
    url: https://www.justperfecthome.com
  - name: Alexs Portfolio
    url: https://panluvme.github.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""Check here for real-time updates on service status, including outages and maintenance. Thank you for being patient with us! 💖
  # introMessage: test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
